package com.lybeat.lilyplayer.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lybeat.lilyplayer.entity.PlayRecord;

import com.lybeat.lilyplayer.entity.PlayRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playRecordDaoConfig;

    private final PlayRecordDao playRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playRecordDaoConfig = daoConfigMap.get(PlayRecordDao.class).clone();
        playRecordDaoConfig.initIdentityScope(type);

        playRecordDao = new PlayRecordDao(playRecordDaoConfig, this);

        registerDao(PlayRecord.class, playRecordDao);
    }
    
    public void clear() {
        playRecordDaoConfig.getIdentityScope().clear();
    }

    public PlayRecordDao getPlayRecordDao() {
        return playRecordDao;
    }

}
